version: '3.8'

services:
    app:
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        image: app:django
        container_name: django_container
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        depends_on:
        - db
        networks:
        - djangonetwork


    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'JustDB'
            MYSQL_USER: 'user'
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        networks:
            - djangonetwork

networks:
    djangonetwork:
        driver: bridge